 # `npm bin`/decktape '--chrome-arg=--allow-file-access-from-files' '1_2_IntroductionToMedfate.html' '1_2_IntroductionToMedfate.pdf'
 # `npm bin`/decktape '--chrome-arg=--allow-file-access-from-files' '1_3_ModelInputs.html' '1_3_ModelInputs.pdf'
 # `npm bin`/decktape '--chrome-arg=--allow-file-access-from-files' '1_4_ModelInputs_exercise.html' '1_4_ModelInputs_exercise.pdf'
 # `npm bin`/decktape '--chrome-arg=--allow-file-access-from-files' '2_2_ForestWaterEnergyBalance_practice.html' '2_2_ForestWaterEnergyBalance_practice.pdf'
 # `npm bin`/decktape '--chrome-arg=--allow-file-access-from-files' '2_3_ForestWaterEnergyBalance_exercise.html' '2_3_ForestWaterEnergyBalance_exercise.pdf'
  `npm bin`/decktape '--chrome-arg=--allow-file-access-from-files' '3_2_ForestGrowthDynamics_practice.html' '3_2_ForestGrowthDynamics_practice.pdf'
#`npm bin`/decktape '--chrome-arg=--allow-file-access-from-files' '3_2_ForestGrowthDynamics_exercise.html' '3_2_ForestGrowthDynamics_exercise.pdf'
