---
title: "Course information"
author: "Miquel De Cáceres"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

## Presentation

+ **Title** - Process-based forest modelling using the **medfate** and **medfateland** R packages
+ **Who** - Miquel De Cáceres (EMF-CREAF), Rodrigo Balaguer-Romano (EMF-CREAF)
+ **When** - 19-21 November 2024 (9-14h, 16-18h)
+ **Recommended for** - Forest engineers and forest ecologists at any point of their career interested in learning how to conduct process-based modelling of forest function and dynamics 
+ **Organization** - Francisco Mauro. Universidad de Valladolid, Campus de Soria
+ **Description** - The main aims of the course are: (a) to provide participants with the basis to understand the formulation and parameterization of biophysical, physiological and ecological processes in the models of forest water balance, carbon balance and forest dynamics included in the R package medfate; (b) to show how to use  **medfate** and **medfateland** R packages to prepare model inputs, perform simulations of forest function and dynamics at stand to regional scales.

## Requirements

 + Students should be able to program scripts in R (including loops and conditionals) and should understand common R data structures (data frames, lists, vectors, etc.).

## Questions for inscription

 + Do you have experience programming in R (i.e. writing your own R scripts)?
 + Have you used process-based forest models in the past? If yes, indicate which models did you use.
 + Have you used the **medfate** and **medfateland** R packages so far? If yes, briefly explain the context.
   
## Content and temporal organization

+ Day 1 (Nov. 19th) - Session 1 (9-14h): 
  - 1.1 Introduction to process-based forest modelling (theory; 30 min)
  - 1.2 Introduction to the **medfate** modelling framework (theory; 30 min)
  - 1.3 Model inputs (practice; 1h)
  - 1.4 Model inputs (exercises; 2h)
+ Day 1 (Nov. 19th) - Session 2 (16-18h): 
  - 1.5 Practice creating inputs with your own data (2h).
+ Day 2 (Nov. 20th) - Session 3 (9-14h):
  - 2.1 Design and formulation of forest water/energy balance in **medfate** (theory; 1h)
  - 2.2 Forest water/energy balance (practice; 1h)
  - 2.3 Forest water/energy balance (exercises; 2h)
+ Day 2 (Nov. 20th) - Session 4 (16-18h):
  - 3.1 Design and formulation of forest carbon balance and forest dynamics in **medfate** (theory; 1h)
  - 3.2 Forest growth and dynamics (practice; 1h)
+ Day 3 (Nov. 21th) - Session 5 (9-14h):
  - 3.3 Forest growth and dynamics (exercises; 2h)
  - 4.1 Preparing model inputs and launching landscape/regional simulations using **medfateland** (practice; 1h)
  - 4.2 Large-scale simulations (exercises; 1h)
+ Day 3 (Nov. 21th) - Session 6 (16-18h):
  - 4.2 Large-scale simulations, cont. (exercises; 1h)
  - 4.3 Species parameter estimation using **traits4models** (practice; 30 min)
  - 4.4 Closure and feedback (30 min)
